/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eric_burgers;

import eric_burgers.GUI.HomePage;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.util.Duration;
/**
 * Application
 */
public class App extends Application{
    public String getGreeting() {
        return "Hello world.";
    }
    private Stage stage;
    /**
     * Starts the program
     * @param primaryStage this is the primary stage that will be displayed
     */
    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        HomePage homePage = new HomePage(stage);
        Scene scene = homePage.createScene();
        primaryStage.setTitle("Erics Burgers");
        primaryStage.setScene(scene);
        primaryStage.show();
    }
    public static void main(String[] args) {
        launch(args);
    }
}
